Populate exam authorizations with coupon codes
mitodl/micromasters pull request #4651
Opened 2020-09-22 12:49 UTC by annagav

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Related to #4648

#### What's this PR do?
Adds a management command to process a csv file with edx coupon urls 
Add a new field to ExamAuthorization

#### How should this be manually tested?
Run migrations
In django shell set up an exam run. 
Create few exam authorizations for users with status `success`. 
Run the managements command `populate_edx_exam_coupons` with a provided csv file.

2020-09-30 19:55 UTC, noisecapella requested changes

2020-09-30 19:55 UTC, noisecapella commented on exams/management/commands/populate_edx_exam_coupons.py
> +        parser.add_argument('csvfile', type=argparse.FileType('r'), help='')
That's neat, I didn't know you could have files handled this way

2020-09-30 19:55 UTC, noisecapella commented on static/js/components/dashboard/courses/StatusMessages.js
> +        <a href={course.exam_url}>
Should we do the same check for `course.exam_url` in the if statement like we're doing below?

2020-09-30 19:57 UTC, noisecapella commented
Should we change the edX.org on this card too? ![Screenshot from 2020-09-30 15-55-11](https://user-images.githubusercontent.com/863262/94733204-66eead00-0335-11eb-9ed8-28e167a42b9b.png)

2020-10-01 19:46 UTC, annagav commented
@noisecapella what did you mean in your last comment about the exam card?

2020-10-06 13:08 UTC, annagav commented
@noisecapella I think I addressed all of your comments. Thanks!

2020-10-06 16:59 UTC, noisecapella requested changes

2020-10-06 16:59 UTC, noisecapella commented on exams/management/commands/populate_edx_exam_coupons.py
> +        if auths_changed:
Can we write out `Authorizations changed` even when the number is 0? I think it would help prevent confusion here.

2020-10-06 17:01 UTC, noisecapella commented
Functionality works great, just one comment

2020-10-06 19:27 UTC, noisecapella approved these changes

2020-10-09 11:22 UTC, merged