Update populate_exam_coupons command to parse course number
mitodl/micromasters pull request #4671
Opened 2020-10-27 18:04 UTC by annagav

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Fix #4669 

#### What's this PR do?
Update populate_exam_coupons command to parse course number

#### How should this be manually tested?
Run the command with the new file that has the course number in the column "Catalog Query".

2020-10-29 16:18 UTC, noisecapella requested changes

2020-10-29 16:18 UTC, noisecapella commented on exams/management/commands/populate_edx_exam_coupons.py
> +        course_number = re.search(r"key:\(([A-Za-z0-9.]+)", catalog_query)
This returns a `Match` object which causes an error below in the `Course.objects.filter` line

2020-10-29 17:25 UTC, annagav commented
@noisecapella could you try again?

2020-10-30 18:37 UTC, noisecapella requested changes

2020-10-30 18:37 UTC, noisecapella commented on exams/management/commands/populate_edx_exam_coupons.py
> +        if course is None:
Can we change this to use `Course.objects.get` instead? That way there is only one course which matches.

2020-10-30 19:24 UTC, noisecapella approved these changes

2020-10-30 19:39 UTC, merged