Process proctored exam grade report form edX
mitodl/micromasters pull request #4679
Opened 2020-11-04 22:16 UTC by annagav

#### Pre-Flight checklist

#### What are the relevant tickets?
Fix #4668

#### What's this PR do?
Add a management command for processing  proctored exam grade report form edX

#### How should this be manually tested?
In django shell set up an ExamRun that is currently schedulable. Make sure your user paid for the course.
Run the command `./manage.py import_edx_exam_grades 14.100`

2020-11-16 17:40 UTC, noisecapella requested changes

2020-11-16 17:40 UTC, noisecapella commented on exams/management/commands/import_edx_exam_grades.py
> +        reader = csv.DictReader(csvfile.read().splitlines())
It doesn't look like you need the `read().splitlines()` part here. `DictReader` can read from file handles directly

2020-11-16 17:40 UTC, noisecapella commented on exams/management/commands/import_edx_exam_grades.py
> +        parser.add_argument('course_code', type=argparse.FileType('r'), help='Example: 14.100')
Is this supposed to be a `FileType`?

2020-11-16 17:40 UTC, noisecapella commented on exams/management/commands/import_edx_exam_grades.py
> +        exam_run = ExamRun.get_currently_schedulable(course).first()
Can we use `except ExamRun.DoesNotExist` here, and also `ExamRun.MultipleObjectsReturned` to detect if there are more than one matching `ExamRun`?

2020-11-19 16:57 UTC, annagav commented
@noisecapella I addressed all your comments. Thank you!

2020-12-02 14:46 UTC, noisecapella approved these changes

2020-12-02 19:15 UTC, merged