Fix selenium tests running locally
mitodl/micromasters pull request #4726
Opened 2020-12-02 10:57 UTC by umarmughal824

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2020-12-03 17:49 UTC, noisecapella commented
Can we make a more specific fix for this issue? I saw only one error:
![Screenshot from 2020-12-03 12-45-25](https://user-images.githubusercontent.com/863262/101067400-81c3e480-3565-11eb-99c8-e25d883a0e9b.png)

There is a list of ignored console messages here. Can you add a part of the message to this list? https://github.com/mitodl/micromasters/blob/497b331caaeda2e323b6ef20b8227ef3c5dc6036/selenium_tests/util.py#L30

2020-12-04 11:00 UTC, umarmughal824 commented
@noisecapella Could you please mention the steps to see that warning so that I could test it after adding it in the ignored log messages?

2020-12-04 14:30 UTC, noisecapella commented
It should be enough to just run `./script/tests/run_selenium_tests_dev.sh` like you have been. You may need to run migrations first if you have a stale instance: `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.selenium.yml run web ./manage.py migrate`

2020-12-04 19:19 UTC, umarmughal824 commented
@noisecapella Every time I run that command `/scripts/test/run_selenium_tests_dev.sh`, it never showed that error and every time got passed.

2020-12-08 14:10 UTC, umarmughal824 commented
@noisecapella waiting for your final review.

2020-12-10 22:11 UTC, noisecapella requested changes

2020-12-10 22:11 UTC, noisecapella commented on selenium_tests/basic_test.py
> +    browser.get("/a-program-title/", ignore_errors=True)
Can we leave out `ignore_errors`?

2020-12-11 00:15 UTC, umarmughal824 commented on selenium_tests/basic_test.py
> +    browser.get("/a-program-title/", ignore_errors=True)
removing it will fail the test.

2020-12-11 13:43 UTC, noisecapella approved these changes

2020-12-11 13:57 UTC, merged