adding documentation for edX exam management commands
mitodl/micromasters pull request #4822
Opened 2021-03-12 22:53 UTC by annagav

#### What are the relevant tickets?
none

#### What's this PR do?
adding documentation for edX exam management commands

#### How should this be manually tested?
read the file

2021-03-23 18:41 UTC, pdpinch requested changes
Thanks, this is great. 

Just one clarification and a one typo fix.

2021-03-23 18:41 UTC, pdpinch commented on exams/README.md
> +This management command takes one argument, the csv file. Each file contains coupon codes for one
```suggestion
This management command takes one argument, the csv file as provided by edX. Each file contains coupon codes for one 
```

2021-03-23 18:41 UTC, pdpinch commented on exams/README.md
> +This management command users the course_id in each row to find the course and corresponding ExamRun
typo

```suggestion
This management command uses the course_id in each row to find the course and corresponding ExamRun 
```

2021-03-25 17:36 UTC, annagav commented
@pdpinch is this good to merge?

2021-03-25 17:37 UTC, pdpinch approved these changes
👍

2021-03-25 17:40 UTC, merged