Show an error message on checkout request failure
mitodl/micromasters pull request #4827
Opened 2021-03-15 15:27 UTC by arslanashraf7

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#4825 

#### What's this PR do?
- Adds an error message along with support link in case of API failure on the Order Summary page, Previously there was no error shown in case of failure

#### How should this be manually tested?
The steps to reproduce this are explained in detail in https://github.com/mitodl/micromasters/issues/4823.

#### Screenshots (if appropriate)
**Desktop**
<img width="500" alt="Screenshot 2021-03-15 at 8 25 21 PM" src="https://user-images.githubusercontent.com/34372316/111178109-a6037880-85cc-11eb-96ef-cf2032ee23b8.png">

**Mobile**
<img width="1437" alt="Screenshot 2021-03-15 at 8 25 11 PM" src="https://user-images.githubusercontent.com/34372316/111178093-a26ff180-85cc-11eb-9d9d-c3986fd8f148.png">

2021-03-15 15:33 UTC, arslanashraf7 commented
@pdpinch, Could you take a look at the screenshots and let me know if anything needs to change.

I also tried it with a toast(which will display for a couple of seconds) but that didn't seem like a good option to show an error to the user with an actionable link e.g. Zendesk (Adding that screenshot below).

<img width="1236" alt="Screenshot 2021-03-15 at 8 31 44 PM" src="https://user-images.githubusercontent.com/34372316/111179267-b49e5f80-85cd-11eb-93b9-953802577179.png">

2021-03-15 18:46 UTC, annagav approved these changes
Functionality works well 👍  If @pdpinch is okay with the ui feel free to merge.

2021-03-15 19:08 UTC, pdpinch commented on static/js/components/OrderSummary.js
> +                customer support
```suggestion
              Something went wrong. Please {" "}
              <a
                href="https://mitx-micromasters.zendesk.com/hc/en-us/requests/new"
                target="_blank"
                rel="noopener noreferrer"
              >
                contact customer support.
```

2021-03-15 19:08 UTC, pdpinch requested changes
I requested some text tweaks

2021-03-16 08:21 UTC, arslanashraf7 commented
@pdpinch, Addressed your feedback. Screenshots in the description have also been updated.

2021-03-17 12:35 UTC, pdpinch approved these changes

2021-03-17 12:35 UTC, pdpinch approved these changes
please merge asap

2021-03-17 12:36 UTC, merged