use uuid based hashes for certificates
mitodl/micromasters pull request #4963
Opened 2021-06-23 11:33 UTC by HamzaIbnFarooq

#### Pre-Flight checklist
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
None

#### What's this PR do?
It uses UUID based hashes for certificates to make the URLs unpredictable

#### How should this be manually tested?
Create program and course certificates the hash should be working fine, secondly, the old certificates and their hashes should not be disturbed.

2021-06-28 17:03 UTC, annagav requested changes
We also need to update hash generation in factories.py the creation of `MicromastersCourseCertificateFactory` and `MicromastersProgramCertificateFactory`

2021-06-28 17:08 UTC, annagav commented
Also please remove `generate_md5` function fro `micromasters/utils.py`. I don't think it is needed any longer.

2021-06-29 06:06 UTC, HamzaIbnFarooq commented
Thanks, Anna for the review.

> We also need to update hash generation in factories.py the creation of `MicromastersCourseCertificateFactory` and `MicromastersProgramCertificateFactory`

I have already changed the hash mechanism for `MicromastersCourseCertificateFactory` in this PR at https://github.com/mitodl/micromasters/pull/4963/files#diff-75b41e76db697a24ee58812d32897e2257d2c215d173d2cafcde3e0054bbe42bR72. Although I will add the hash for `MicromastersProgramCertificateFactory` now.

> Also please remove generate_md5 function fro micromasters/utils.py. I don't think it is needed any longer.

generate_md5 is being used in two migrations 1) https://github.com/mitodl/micromasters/blob/master/dashboard/migrations/0008_programenrollment_hash.py and 2) https://github.com/mitodl/micromasters/blob/master/grades/migrations/0014_remove_micromasterscoursecertificate_final_grade.py so I don't think it's possible to get rid of that without applying some hack here, do you have any thoughts on this?

2021-06-29 17:48 UTC, annagav approved these changes
Looks good 👍

2021-06-30 06:10 UTC, merged