fix: enable enrollment for courses with past upgrade deadline
mitodl/micromasters pull request #4984
Opened 2021-07-15 11:02 UTC by arslanashraf7

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
#4975 

#### What's this PR do?
- Enabled the enrollment for courses that have an upgrade deadline I the past
- fixes the display for `View on edX` and enrollment buttons

#### How should this be manually tested?
Steps from #4975 can be followed to test it

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2021-07-15 18:33 UTC, annagav requested changes
I think we should remove the option to pay in the dialog. Or disable it and add a message saying the the deadline to upgrade has passed, so they can't pay.

2021-07-15 18:36 UTC, annagav commented
Also, the are two messages are a somewhat confusing. The course progress message says "course stared" and the course status message says "course is starting"

2021-07-16 13:00 UTC, arslanashraf7 commented
> I think we should remove the option to pay in the dialog. Or disable it and add a message saying the the deadline to upgrade has passed, so they can't pay.

@annagav I've updated the PR with the below changes, let me know your thoughts:
1. Updated course status/progress messages in case of the future enrollment end date and past course start date.
2. Disabled the `Pay Now` button based on `Upgrade deadline`, if the `course upgrade deadline` is in past then the `Pay Now` button will be disabled for all the users either they are new or they come to upgrade the course due to other reason.

If the above perception is okay with you, I'll mark the PR ready for review.

2021-07-16 18:28 UTC, annagav commented
@pdpinch @briangrossman could you confirm that the copy changes are okay.

2021-07-20 12:30 UTC, annagav commented
@pdpinch @briangrossman Could you confirm the new dialog message "You can't pay for this course. The deadline to upgrade the course has passed."

2021-07-20 12:52 UTC, pdpinch commented on static/js/components/CourseEnrollmentDialog.js
> +          passed.
```suggestion
          You cannot pay for this course at this time. The payment deadline has passed.
```

2021-07-20 12:54 UTC, pdpinch commented
Will this message apply to all programs, i.e. both the fa program (DEDP, with it's proctored exam system) and the non-fa programs (e.g. SCM) ?

Can you update the screenshot?

2021-07-26 09:15 UTC, arslanashraf7 commented
> Will this message apply to all programs, i.e. both the fa program (DEDP, with it's proctored exam system) and the non-fa programs (e.g. SCM) ?

Yes, it will be applied to both FA and Non-FA programs. However, the order of messages shown based on the conditions for FA programs can be seen in the screenshot descriptions.

Code reference for the order of messages for FA is listed below in orderly fashion from top-bottom:
- [Personal price is in pending state](https://github.com/mitodl/micromasters/blob/d4ffaa685127e22b0fae127e1b994d1f6dbb9d5c/static/js/components/CourseEnrollmentDialog.js#L89)
- [User has already paid](https://github.com/mitodl/micromasters/blob/d4ffaa685127e22b0fae127e1b994d1f6dbb9d5c/static/js/components/CourseEnrollmentDialog.js#L109)
- [Upgrade deadline has passed](https://github.com/mitodl/micromasters/blob/d4ffaa685127e22b0fae127e1b994d1f6dbb9d5c/static/js/components/CourseEnrollmentDialog.js#L125)
- [Personal price is approved/User had applied](https://github.com/mitodl/micromasters/blob/d4ffaa685127e22b0fae127e1b994d1f6dbb9d5c/static/js/components/CourseEnrollmentDialog.js#L144)
- [User has not calculated the personal price](https://github.com/mitodl/micromasters/blob/d4ffaa685127e22b0fae127e1b994d1f6dbb9d5c/static/js/components/CourseEnrollmentDialog.js#L165)
 
> Can you update the screenshot?

Updated

2021-08-02 11:58 UTC, annagav approved these changes
looks good 👍

2021-08-02 12:44 UTC, merged

2021-08-02 13:11 UTC, annagav commented
@umarmughal824 I am sorry for the misunderstanding, but Peter and Brian have to confirm your text changes.

2021-08-02 14:26 UTC, briangrossman commented
👍 
I'm fine with this as is.

I'm going to create a new issue with some minor text tweaks, but this PR can be released.