Program Letter: added css to hide footer on print
mitodl/micromasters pull request #5004
Opened 2021-08-04 10:23 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Ticket #4988 

#### What's this PR do?
Removes Footer in Program Letter on Printing/Print Preview

#### How should this be manually tested?
- Create a Program Letter if one does not exist.
- Go to the Program Letter url '/letter/program/<program_letter_uuid>' 
- Verify footer is visible.
- Press CTRL+P to open print preview.
- Verify footer is hidden.

#### Screenshots (if appropriate)
Program Letter page with footer visible.
<img width="1408" alt="Screenshot 2021-08-03 at 3 57 49 PM" src="https://user-images.githubusercontent.com/87968618/128010117-3bd0d0a7-7a56-47a8-97ec-85802e89d4be.png">

Print preview with footer hidden.
![image](https://user-images.githubusercontent.com/87968618/128009984-c739edb7-ba71-43e0-9165-f98d7a8b2c8c.png)

2021-08-04 11:56 UTC, umarmughal824 requested changes
please fix tests

2021-08-04 12:29 UTC, Wassaf-Shahzad commented
> please fix tests

I believe the selenium test are falling due to broken selenium container  as referenced here (https://github.com/mitodl/micromasters/pull/5003).

2021-08-04 12:45 UTC, umarmughal824 commented
> > please fix tests
> 
> I believe the selenium test are falling due to broken selenium container as referenced here (#5003).

Lets wait for to get #5003 to get merged and you will have to rebase it to get rid off that tests failure

2021-08-05 09:22 UTC, umarmughal824 requested changes
please squash your commits

2021-08-05 11:47 UTC, umarmughal824 approved these changes
👍

2021-08-05 13:41 UTC, merged