added resource page and privacy policy page pre-population migration
mitodl/micromasters pull request #5032
Opened 2021-09-01 15:12 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
- [x] Migrations
  - [x] Migration is backwards-compatible with current production code
- [ ] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Ticket #5025 

#### What's this PR do?
Adds privacy policy page.

#### How should this be manually tested?

Run migrations and visit /privacy-policy/
ensure page is visible and correct styles have been applied 

#### Screenshots (if appropriate)
Desktop Screen shots:

![Screenshot 2021-09-01 at 7 09 24 PM](https://user-images.githubusercontent.com/87968618/131697066-eb8117ab-1654-4a2c-b215-ee9473eddb5b.png)

Mobile screent shots

![Uploading Screenshot 2021-09-01 at 7.10.07 PM.png…]()

2021-09-01 15:21 UTC, Wassaf-Shahzad commented
(for prosperity)
I ran into an issue in micromasters, If I create a migration file for the resource page and restart the docker container it fails during applying migrations (0004_create_homepage) .However if I delete the migration file for resource page,The container restarts successfully.
If I create and apply migrations from a running container they succeed as well.
The error the docker container gives is a Null constraint failure on field locale_id while creating the home_page.
After a bit RnD I did work out a solution which was adding the following code to migration file (0004_create_homepage)
run_before = [
        ('wagtailcore', '0053_locale_model'),
    ]
in reference to https://stackoverflow.com/questions/65369636/wagtail-locale-id-cannot-be-null (edited)

2021-09-02 12:48 UTC, Wassaf-Shahzad commented on static/scss/resource.scss
> +
I am sorry @pdpinch, I was unable to identify any css that we could inherit as most  of our styles in micromasters are scoped (in my knowledge).

2021-09-02 15:45 UTC, pdpinch reviewed
screenshots look good to me.

2021-09-02 15:58 UTC, briangrossman commented
@Wassaf-Shahzad 
It looks like you're making good progress on this. It's looking very good. 

A couple notes: 
- Can you include the page header in the screenshot so we can see the page in context? 
- The link to the mobile design isn't working. Can you repost the mobile version? 
- Can you change the title to `Privacy Policy` (remove the hyphen `-`)
- Please make sure the red/cardinal color around `Privacy Policy` is the same color as the header background (I think it's slightly different right now)

2021-09-03 05:24 UTC, Wassaf-Shahzad commented
> @Wassaf-Shahzad
> It looks like you're making good progress on this. It's looking very good.
> 
> A couple notes:
> 
> * Can you include the page header in the screenshot so we can see the page in context?
> * The link to the mobile design isn't working. Can you repost the mobile version?
> * Can you change the title to `Privacy Policy` (remove the hyphen `-`)
> * Please make sure the red/cardinal color around `Privacy Policy` is the same color as the header background (I think it's slightly different right now)

@briangrossman 

>* I have included the screenshot of the whole page.
>* Sorry for the that, I  have added mobile screenshots as well.
>* Updated title swell.
>* Changed the color around `Privacy Policy` and can be viewed in the new screenshot.

Thank you

2021-09-03 16:15 UTC, briangrossman commented
@Wassaf-Shahzad 
These designs look good to me. 👍 
Nice job. 

Can you also provide a screenshot of the CMS page for administering this page as well as the updated footer?

2021-09-07 07:06 UTC, Wassaf-Shahzad commented
> @Wassaf-Shahzad
> These designs look good to me. 👍
> Nice job.
> 
> Can you also provide a screenshot of the CMS page for administering this page as well as the updated footer?

Added requested screenshots.

2021-09-08 14:22 UTC, briangrossman commented
> > @Wassaf-Shahzad
> > These designs look good to me. 👍
> > Nice job.
> > Can you also provide a screenshot of the CMS page for administering this page as well as the updated footer?
> 
> Added requested screenshots.

Thanks. Looks good to me. Thanks. 👍

2021-09-08 15:25 UTC, annagav requested changes
The sign in button doesn't seem to work on the Privacy Policy page.

2021-09-08 16:03 UTC, Wassaf-Shahzad commented
> The sign in button doesn't seem to work on the Privacy Policy page.

Sorry about that, I have updated page as needed.

2021-09-09 14:14 UTC, annagav approved these changes
👍

2021-09-10 05:28 UTC, merged