fix degree and employment form fields on mobile level
mitodl/micromasters pull request #5034
Opened 2021-09-02 12:53 UTC by umarmughal824

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
fixes #5019 

#### What's this PR do?
Can't select some countries in pulldowns on phone in portrait mode

#### How should this be manually tested?
Just see the country field on the profile page by adding degree and employment 

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2021-09-02 15:12 UTC, briangrossman commented
@umarmughal824 - Visually, the screenshots you shared look great! I think the longest country is:
`Ascension and Tristan Da Cunha, Saint Helena`, it would be good to check that one, in particular.

2021-09-03 07:33 UTC, umarmughal824 commented
@briangrossman this is how it looks like
<img width="467" alt="Screenshot 2021-09-03 at 12 30 47" src="https://user-images.githubusercontent.com/4043989/131967805-7b79bc55-37fe-43a7-b75b-f37e34065e48.png">
<img width="448" alt="Screenshot 2021-09-03 at 12 30 56" src="https://user-images.githubusercontent.com/4043989/131967815-035dd3f8-f9f8-4d87-b902-7062c8390322.png">

2021-09-03 16:27 UTC, briangrossman commented
> @briangrossman this is how it looks like
> 
> <img alt="Screenshot 2021-09-03 at 12 30 47" width="467" src="https://user-images.githubusercontent.com/4043989/131967805-7b79bc55-37fe-43a7-b75b-f37e34065e48.png">

Great. Thanks!!! 👍

2021-09-07 12:17 UTC, umarmughal824 commented
@annagav could you please review it?

2021-09-09 14:27 UTC, annagav requested changes
Could we achieve the same result on mobile view without also modifying the full desktop view of the card?

2021-09-09 14:36 UTC, umarmughal824 commented
@briangrossman do you think should we should update the desktop screens or should we keep them intact as per the attached screenshots.

2021-09-09 15:10 UTC, briangrossman commented
@umarmughal824 

If possible, I think it would be better to have this PR only only affect the mobile view. Ideally, the desktop would continue to look like it currently does on the production site, rather than modifying it:

![image](https://user-images.githubusercontent.com/21342568/132712435-40295c6d-a2a1-4d81-a18e-365b04bdb003.png)

2021-09-09 19:45 UTC, annagav commented
@briangrossman this is how it used to be before:


<img width="1069" alt="Screen Shot 2021-09-09 at 9 43 00 PM" src="https://user-images.githubusercontent.com/7574259/132752487-2ccbbf96-d37f-4b40-9ff8-a62521657c82.png">
and here is in this PR:
<img width="1071" alt="Screen Shot 2021-09-09 at 9 44 01 PM" src="https://user-images.githubusercontent.com/7574259/132752494-126a4d80-4405-4132-abf0-7e0e0f254679.png">

2021-09-10 09:46 UTC, umarmughal824 commented
> @briangrossman this is how it used to be before:
> 
> <img alt="Screen Shot 2021-09-09 at 9 44 01 PM" width="1071" src="https://user-images.githubusercontent.com/7574259/132752494-126a4d80-4405-4132-abf0-7e0e0f254679.png">
> 
> and here is in this PR:
> <img alt="Screen Shot 2021-09-09 at 9 43 00 PM" width="1069" src="https://user-images.githubusercontent.com/7574259/132752487-2ccbbf96-d37f-4b40-9ff8-a62521657c82.png">

check the updated screenshots attached in the PR description.

2021-09-10 09:50 UTC, umarmughal824 commented
@briangrossman @annagav I have updated the screenshots see in the PR description.

2021-09-10 13:48 UTC, briangrossman commented
> @briangrossman @annagav I have updated the screenshots see in the PR description. I have updated the tablet version too as it seems problematic.

@umarmughal824 Thanks! I see what you're saying with the wrapping of the city field for the tablet version. Thanks for sharing that. 

I think it's fine the way you have it now. The most important thing is that you've fixed the options in the pulldown so they don't overlap.

2021-09-17 12:31 UTC, annagav approved these changes
LGTM 👍

2021-09-17 12:56 UTC, merged