asadiqbal08/ WIP -- Migrating from ElasticSearch to OpenSearch (In Progress)
mitodl/micromasters pull request #5166
Opened 2022-02-07 13:14 UTC by asadiqbal08

#### What are the relevant tickets?
fixes: https://github.com/mitodl/micromasters/issues/5155

#### What's this PR do?
Migrating from Elasticsearch to OpenSearch

#### NOTE: WORK IN PROGRESS ( IT IS PROTOTYPE)

2022-02-08 22:12 UTC, pdpinch commented
It's going to be at least a few days before @mitodl/devops will be able to set up a opensearch cluster for you to test with. In the meantime can you help them with some more information:

- What API endpoints does this app use?
- What are the names of the indexes that we will need?

This will help them with setting up permissions and access controls.

2022-02-09 16:19 UTC, asadiqbal08 commented
> What API endpoints does this app use?

@pdpinch If I looked around the codebase then these [URL](https://github.com/mitodl/micromasters/blob/master/search/urls.py#L8) is used along with ElasticSearch query data to get results. As an example:

![screencapture-mm-odl-local-8079-api-v0-search-2022-02-09-20_40_48](https://user-images.githubusercontent.com/7334669/153235656-86ac494c-4214-4d03-b1dc-fa6810d9989c.png)

<img width="625" alt="Screenshot 2022-02-09 at 9 10 45 PM" src="https://user-images.githubusercontent.com/7334669/153241596-cb0e84a1-67f6-44d9-b926-8a78039b9a0f.png">


> What are the names of the indexes that we will need?

I used this setting locally for `OPENSEARCH_INDEX='micromaster'` and [this](https://github.com/mitodl/micromasters/blob/master/search/connection.py#L97-L112) is basically making alias names but I believe DevOps have to look around these settings while configuring over Heruko.

```
HEROKU_PARENT_APP_NAME
HEROKU_APP_NAME
```

2022-02-11 20:55 UTC, pdpinch commented
I think @blarghmatey wanted to know the elasticsearch endpoints that the MIcroMasters app hits. One of his bigger tasks will be updating the access controls around those endpoints, because that's different in the AWS service than in our own cluster.

2022-03-02 15:17 UTC, Ardiea commented
> I think @blarghmatey wanted to know the elasticsearch endpoints that the MIcroMasters app hits. One of his bigger tasks will be updating the access controls around those endpoints, because that's different in the AWS service than in our own cluster.

This would still be very good information to have in the near-ish future. I'm starting to look at spinning up opensearch clusters for you this week/next week, I believe. I opened https://github.com/mitodl/ol-infrastructure/issues/639 to track the work on the devops side.

2022-03-08 18:39 UTC, Ardiea commented
@asadiqbal08 

https://github.com/mitodl/ol-infrastructure/pull/647

I have created these OpenSearch clusters in CI, QA, and Production. I have written the code to hook the Read-Only IAM policy up to MIT-Open but I have not run it and I have not written anything else (I think only micromasters remains?). If you need the details on the policy ARNs I can get hose for you. LMK how I can help further!

2022-03-16 13:18 UTC, asadiqbal08 commented
@Ardiea can we deploy this PR changes to CI environment to test the OpenSearch functional behavior and its searching endpoints ?

2022-03-21 23:42 UTC, pdpinch commented
@asadiqbal08 can you rebase this?

I tried clicking on "Create Review app" in the Heroku dashboard for you, but I got the following errors:

```
"OPENSEARCH_HTTP_AUTH" is required, config var "OPENSEARCH_SHARD_COUNT" is required, config var "OPENSEARCH_INDEX" is required, config var "OPENSEARCH_URL" is required • View log 
```

2022-03-22 07:34 UTC, asadiqbal08 commented
Rebased. I guess you need to set these vars. Devops can help out about them. 

```
ELASTICSEARCH_INDEX=`micromaster`
OPENSEARCH_URL=https://(your_open_search_url ) for connecting to OpenSearch cluster.
OPENSEARCH_HTTP_AUTH=(your_cluster_name):(key) (Basic auth settings for connecting to Opensearch)
```

2022-06-14 20:38 UTC, annagav requested changes
Code looks good, just a minor comment. Going to test functionality

2022-06-14 20:38 UTC, annagav commented on search/indexing_api_test.py
> +# from elasticsearch.exceptions import NotFoundError
could you remove this

2022-06-14 22:34 UTC, annagav commented
Functionality looks good 👍

2022-06-30 07:55 UTC, asadiqbal08 commented
@annagav should I merge it ?

2022-06-30 12:52 UTC, annagav approved these changes
👍

2022-07-01 06:37 UTC, merged