WIP -- Use MitxOnline usernames
mitodl/micromasters pull request #5180
Opened 2022-03-18 11:36 UTC by asadiqbal08

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
fixes: #5163 

#### What's this PR do?
The `import_edx_exam_grades` management command should be updated to use usernames from MITx Online.

#### How should this be manually tested?
Run the command with the `CSV` (That assume to have usernames from MitxOnline provider)

2022-03-22 12:52 UTC, annagav requested changes
Just a couple minor comments

2022-03-22 12:52 UTC, annagav commented on exams/management/commands/import_edx_exam_grades.py
> +            user_social_auth = UserSocialAuth.objects.filter(uid=row['username'], provider='mitxonline')
could you use a constant here `BACKEND_MITX_ONLINE` instead of 'mitxonline'

2022-03-22 12:52 UTC, annagav commented on exams/management/commands/import_edx_exam_grades.py
>                      self.style.ERROR('Could not find user for username {}'.format(row['username']))
Could you update the message about not fining social auth for user

2022-03-25 12:20 UTC, asadiqbal08 commented
@annagav any other feedback ?

2022-03-25 14:19 UTC, annagav approved these changes
👍

2022-03-29 10:26 UTC, merged