Removing sign in buttons from DEDP page
mitodl/micromasters pull request #5389
Opened 2024-05-01 21:20 UTC by annagav

### What are the relevant tickets?
Fix https://github.com/mitodl/hq/issues/3936

### Description (What does it do?)
Removes the sign in buttons from the DEDP program page. 
I used a hardcoded id for the program since it is never going to change. I didn't see much value in introducing a constant. We are moving away from the micromsters site.
### Screenshots (if appropriate):
<img width="1168" alt="Screenshot 2024-05-01 at 5 15 05 PM" src="https://github.com/mitodl/micromasters/assets/7574259/d6dcca85-82f9-4593-a7eb-e82dd1179d57">
<img width="1400" alt="Screenshot 2024-05-01 at 5 16 57 PM" src="https://github.com/mitodl/micromasters/assets/7574259/8d955316-4f7c-4424-8f28-7c2985da6df9">

### How can this be tested?
Make sure other pages are unaffected.

2024-05-01 22:17 UTC, pdpinch commented on cms/templates/cms/program_page.html
> +                <a href="https://mitxonline.mit.edu/" class="mdl-button hero-button mdl-cell--hide-phone">
What do you think is the best URL to use for this? Could we go directly to the create-account page?

2024-05-03 13:59 UTC, shanbady requested changes

2024-05-03 13:59 UTC, shanbady commented on cms/templates/cms/program_page.html
> +                <a href="https://mitxonline.mit.edu/create-account/" class="mdl-button hero-button mdl-cell--hide-phone">
not sure how this works locally but could is it possible to use a reverse here?

2024-05-03 15:20 UTC, shanbady approved these changes
looks good. left a minor optional comment

2024-05-03 15:44 UTC, merged